#-----------------------#
# Allgemeine Parameter  #
#-----------------------#
projects            = C:/Users/test/Daten/Java/Projects
runtime             = C:/Users/test/Daten/Java/Applications
libraries           = C:/Users/test/Daten/Java/Libraries

#-----------------------#
# Projekt-Parameter     #
#-----------------------#
project.games       = ${projects}/games
project.source      = ${project.games}/src
project.properties  = ${project.games}/properties
project.metainf     = ${project.games}/META-INF

#-----------------------#
# Laufzeit-Parameter    #
#-----------------------#
runtime.games       = ${runtime}/games
runtime.build       = ${runtime.games}/build
runtime.properties  = ${runtime.games}/properties
runtime.metainf     = ${runtime.games}/META-INF

#-----------------------#
# Bibliotheken          #
#-----------------------#
junit.api           = ${libraries}/junit-5
log4j.api           = ${libraries}/apache-log4j-2.11.1-bin
commons.api         = ${libraries}/commons-io-2.6

#-----------------------#
# Test-Parameter        #
#-----------------------#
project.test      = ${project.games}/test
runtime.test      = ${runtime.games}/test
runtime.output    = ${runtime.games}/output