meta.pc=22H0566
privat.pc = DESKTOP-3NCAR95
schmi.pc = DESKTOP-Q6O0UGB
test.pc = DESKTOP-LERLCJ6

logpath.meta = C:\\Users\\TSZ\\Daten\\Java\\Applications\\games\\logs
logpath.privat = C:\\Users\\Privat\\Daten\\Java\\Applications\\games\\logs
logpath.schmi = C:\\Users\\schmi\\Daten\\Java\\Applications\\games\\logs
logpath.test = C:\\Users\\test\\Daten\\Java\\Applications\\games\\logs

basepath.meta = C:\\Users\\TSZ\\Documents\\ChessBase\\TimBase
basepath.schmi = C:\\Users\\schmi\\Documents\\ChessBase\\TimBase
basepath.privat = C:\\Users\\Privat\\Documents\\ChessBase\\TimBase
basepath.test = C:\\Users\\test\\Documents\\ChessBase\\TimBase

datapath.meta = C:\\Users\\TSZ\\Daten\\ChessBase\\TimBase
datapath.schmi = C:\\Users\\schmi\\Daten\\ChessBase\\TimBase
datapath.privat = C:\\Users\\Privat\\Daten\\ChessBase\\TimBase
datapath.test = C:\\Users\\test\\Daten\\ChessBase\\TimBase

error.host = Kein Computername definiert
frame.title = Partien
display.title = Anzeige
control.title = Steuerung
opening.path = Eroeffnung

button.white = NeuWeiss
button.black = NeuSchwarz
button.timWhite = TimWeiss
button.timBlack = TimSchwarz

button.tournament = Turnier
button.archive = Archiv
button.clear = Leeren
button.book = Buch

button.pushWhite = Push NeuWeiss
button.pushBlack = Push NeuSchwarz
button.pushTimWhite = Push TimWeiss
button.pushTimBlack = Push TimSchwarz
